{
  "website": "http://marcely.de", 
  "commands": {
    "warp": {
      "description": "Essentials /warp with gui.",
      "usage": "/warp"
    },
     "warpcfg": {
      "description": "Configurations for /warp GUI.",
      "usage": "/warpadmin"
    }
  }, 
  "version": 1.6.1, 
  "name": "Essentials_WarpGUI", 
  "author": "Marcely1199", 
  "main": "de.marcely.warpgui.EssentialsWarpGUI", 
  "description": "A plugin for the command /warp.",
}