website: https://marcely.de
version: ${project.version}
name: EssentialsWarpGUI
author: Marcely1199
main: de.marcely.warpgui.EssentialsWarpGUI
description: Adds a GUI to the /warp command
api-version: 1.13
softdepend: [Essentials, EssentialsX]

commands:
    warp:
      description: Essentials /warp with gui
      usage: /warp
    warpcfg:
      description: Configurations for the /warp GUI
      usage: /warpcfg