website: https://marcely.de
version: ${project.version}
name: Essentials_WarpGUI
author: Marcely1199
main: de.marcely.warpgui.EssentialsWarpGUI
description: Adds a GUI to the /warp command

commands:
    warp:
      description: Essentials /warp with gui
      usage: /warp
    warpcfg:
      description: Configurations for the /warp GUI
      usage: /warpcfg